language: android
jdk: openjdk7
android:
  components:
  - buildToolsVersion "23.0.2"
  - android-23
  - extra-android-m2repository
  - extra-android-support
  - sys-img-armeabi-v7a-android-23
  - sys-img-x86-android-17
git:
  submodules: false

script:
- ./gradlew assembleRelease

deploy:
  provider: releases
  user: zhimeiliudan
  password: dan358007232
  api_key: GITHUB OAUTH TOKEN
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
